# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-HStore
version:      0.02
version_from: lib/File/HStore.pm
installdirs:  site
requires:
    Digest::SHA1:                  Digest::SHA2
    File::Copy:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
