# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-HStore
version:      0.06
version_from: lib/File/HStore.pm
installdirs:  site
requires:
    Digest::SHA1:                  0
    Digest::SHA2:                  0
    File::Copy:                    0
    File::Path:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
