--- #YAML:1.0
name:                File-HStore
version:             0.10
abstract:            Perl extension to store files  on a filesystem using a
license:             perl
author:              
    - Alexandre Dulaunoy <adulau@foo.be>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Digest::SHA:                   0
    File::Copy:                    0
    File::Path:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
